datebank/accounts/urls.py
from django.urls import path

from . import views as core_views
from django.conf.urls import url
# from mysite.core import views

urlpatterns = [
	# path('signup/', views.SignUp.as_view(), name='signup'),
	url(r'^signup/$', core_views.signup, name='signup'),
]

datebank/certification82/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView # new
from . import views
#namespacing paths
app_name = 'certification82'
urlpatterns = [
    #!@#$
    path('', views.IndexView.as_view(), name='index'),
    # path('', views.index, name='index'),
    #A-Z
    #A
    path('ai_pro<int:projekt_nr>/show', views.allgeminfo, name='allgeminfo'),
    #B
    #All for betreiber
    path('betreibers/all', views.BetreiberIndexView.as_view(), name='betreiberindex'),
    path('new_betr', views.new_betreiber,name = 'new_betreiber'),
    path('betr/update/<int:pk>', views.BetreiberUpdate.as_view(), name='betreiber_update'),
    path('betr/delete/<int:pk>', views.BetreiberDelete.as_view(), name='betreiber_delete'),
    path('betreiber/number/<int:pk>', views.BetreiberDetailView.as_view(), name = 'betreiberdetailview'),
    
    ###best
    path('bestwind/all', views.BestWindkraftIndexView.as_view(), name='ezebestwindindex'),
    path('bestfoto/all', views.BestFotovoltaicIndexView.as_view(), name='ezebestfotoindex'),
    path('bestgen/all', views.BestGeneratorIndexView.as_view(), name='ezebestgenindex'),
        
    #D
    #DOCUMENTS ALL:
    path('upload_pdf', views.upload_doc, name = 'upload_doc'),
    
    # path('new_document', views.new_document, name = 'new_document'),
    path('alldocs/', views.DocumentIndexView.as_view(), name='documenteindex'),
    path('doc/number/<int:pk>', views.DocumentDetailView.as_view(), name = 'documentdetailview'),
    path('doc/update/<int:pk>', views.DocumentUpdate.as_view(), name='doc_update'),
    path('doc/delete/<int:pk>', views.DocumentDelete.as_view(), name='doc_delete'),
    

    path('neugen/number/<int:pk>', views.NeuGeneratorDetailView.as_view(), name = 'ezeneugendetail'),
    # the 'name' value as called by the {% url %} template tag the DETAIL of the spec proj use id
    path('detail<int:project_id>765525', views.detail, name='detail'),
    
    #E
    #eze
    path('eze_user_detail<int:projekt_nr>', views.eze_user_detail, name = 'eze_user_detail'),
    path('new_eze_bestand', views.new_eze_bestand, name = 'new_eze_bestand'),
    path('new_eze_neu', views.new_eze_neu, name = 'new_eze_neu'),
    path('eze/number/<int:pk>', views.EzeDetailView.as_view(), name = 'ezedetailview'),
    path('eze/update/<int:pk>', views.EzeUpdate.as_view(), name='eze_update'),
    path('ezes/', views.EzeIndexView.as_view(), name='ezeindex'),
    # path('eze/update2/<int:pk>', views.EzeUpdate.as_view(), name='eze_update2'),
    path('eze/delete/<int:pk>', views.EzeDelete.as_view(), name='eze_delete'),
    path('<int:ezeneu_id>/show', views.eze_neu_show, name='eze_neu_show'),
    # path('ezebestdetails/<int:ezebest_id>/', views.eze_best_show, name='eze_best_show'),

    #EZETYP
    
    path('ezetyp/number/<int:pk>', views.EzeTypDetailView.as_view(), name = 'ezetypdetailview'),
    path('ezetyp/update/<int:pk>', views.EzeTypUpdate.as_view(), name='ezetyp_update'),
    path('ezetyps/', views.EzeTypIndexView.as_view(), name='ezetypindex'),
    path('ezetyp/delete/<int:pk>', views.EzeTypDelete.as_view(), name='ezetyp_delete'),
    
    path('new_eze_typ', views.new_eze_typ, name = 'new_eze_typ'),
    
    
    #N
    #NETZBETREIBER HERE:
    path('netzbet/number/<int:pk>', views.NetzbetreiberDetailView.as_view(), name = 'netzbetreiberdetailview'),
    path('netzbet/all', views.NetzbetreiberIndexView.as_view(), name='netzbetreiberindex'),
    path('new_netzbet', views.new_netzbetreiber,name = 'new_netzbetreiber'),
    path('netzbet/update/<int:pk>', views.NetzbetreiberUpdate.as_view(), name='netzbet_update'),
    # path('eze/update2/<int:pk>', views.EzeUpdate.as_view(), name='eze_update2'),
    path('netzbet/delete/<int:pk>', views.NetzbetreiberDelete.as_view(), name='netzbet_delete'),
    
    path('new_hersteller', views.new_hersteller, name = 'new_hersteller'),
    
    path('neuwind/all', views.NeuWindkraftIndexView.as_view(), name='ezeneuwindindex'),
    path('neufoto/all', views.NeuFotovoltaicIndexView.as_view(), name='ezeneufotoindex'),
    path('neugen/all', views.NeuGeneratorIndexView.as_view(), name='ezeneugenindex'),
    
    #O
    #OF THE PROJECT using id
    # path('ezebestands/', views.ezebestands, name='ezebestands'),
    path('ezeneuwindofproj/<int:project_number>/index', views.ezeneuwindkraftsoftheprojectindex, name='ezeneuwindkraftsoftheprojectindex'),
    path('ezeneufotooftheproj/<int:project_id>/index', views.ezeneufotooftheprojectindex, name='ezeneufotooftheprojectindex'),
    path('ezeneugenoftheproj/<int:project_id>/index', views.ezeneugenoftheprojectindex, name='ezeneugenoftheprojectindex'),
    path('ezebestwindoftheproj/<int:project_id>/index', views.ezebestwindoftheprojectindex, name='ezebestwindoftheprojectindex'),
    path('ezebestfotooftheproj/<int:project_id>/index', views.ezebestfotooftheprojectindex, name='ezebestfotooftheprojectindex'),
    path('ezebestgenoftheproj/<int:project_id>/index', views.ezebestgenoftheprojectindex, name='ezebestgenoftheprojectindex'),
    
    #L
    path('login', TemplateView.as_view(template_name='registration/login.html'), name='login'),
    
    #P
    #PROJECT ALL Links:
    
    path('pro<int:project_id>/show', views.project_show, name='project_show'),
    path('pro/update/<int:pk>', views.ProjectUpdate.as_view(), name='project_update'),
    path('pro/delete/<int:pk>', views.ProjectDelete.as_view(), name='project_delete'),
    path('new_projekt', views.new_projekt, name = 'new_projekt'),

    path('pro/number/<int:pk>', views.ProjectDetailView.as_view(), name = 'projectdetailview'),
    
    
    #R
    #RESULTS (about test voting) ex: /polls/5/results/
    path('<int:project_id>/results/', views.results, name='results'),
    
    #T

#T
    path('trafoher/update/<int:pk>', views.TrafoHerstellerUpdate.as_view(), name='trafoher_update'),
    path('trafoher/delete/<int:pk>', views.TrafoHerstellerDelete.as_view(), name='trafoher_delete'),
    path('new_trafoher', views.new_trafohersteller,name = 'new_trafohersteller'),
    path('trafoher/all', views.TrafoHerstellerIndexView.as_view(), name='trafoherstellerindex'),
    path('trafoher/number/<int:pk>', views.TrafoHerstellerDetailView.as_view(), name = 'trafoherstellerdetailview'),
    
    path('trafotyp/update/<int:pk>', views.TrafoTypUpdate.as_view(), name='trafotyp_update'),
    path('trafotyp/delete/<int:pk>', views.TrafoTypDelete.as_view(), name='trafotyp_delete'),
    path('new_trafotyp', views.new_trafotyp,name = 'new_trafotyp'),
    path('trafotyps/', views.TrafoTypIndexView.as_view(), name='trafotypindex'),
    path('trafotyp/number/<int:pk>', views.TrafoTypDetailView.as_view(), name = 'trafotypdetailview'),
    
    path('trafo_user_detail<int:projekt_nr>', views.trafo_user_detail, name = 'trafo_user_detail'),
    path('trafo/update/<int:pk>', views.TransformatorUpdate.as_view(), name='trafo_update'),
    path('trafo/delete/<int:pk>', views.TransformatorDelete.as_view(), name='trafo_delete'),
    path('new_trafo', views.new_trafo,name = 'new_trafo'),
    path('trafos/', views.TransformatorIndexView.as_view(), name='trafoindex'),
    path('trafo/number/<int:pk>', views.TransformatorDetailView.as_view(), name = 'transformatordetailview'),
    

    #V
    # ex: /polls/5/vote/
    path('<int:project_id>/vote/', views.vote, name='vote'),

    #Z
    #ZERTIFIKATINHABER ALL:
    path('new_zert', views.new_zert,name = 'new_zert'),
    path('zer/update/<int:pk>', views.ZertifikatsinhaberUpdate.as_view(), name='zert_update'),
    path('zer/delete/<int:pk>', views.ZertifikatsinhaberDelete.as_view(), name='zert_delete'),
    path('zerts/', views.ZertifikatsinhaberIndexView.as_view(), name='zertifikatsinhaberindexview'),
    path('zerts/number/<int:pk>', views.ZertifikatsinhaberDetailView.as_view(), name = 'zertifikatsinhaberdetailview'),
    
    

    #############################new
    ###docs, betreibers, schutzs, trafos, regelungs list and details
    

    path('schutz/', views.schutzindex, name='schutzindex'),
    # path('schutz/number/<int:pk>', views.SchutzDetailView.as_view(), name = 'documentdetailview'),


    path('regelungindex/', views.regelungindex, name='regelungindex'),
    # path('regel/number/<int:pk>', views.RegelungDetailView.as_view(), name = 'documentdetailview'),

    



    ###wind, foto, generator
    # path('ezebestwindindex/', views.BestWindkraftIndexView.as_view(), name='ezebestwindindex'),
    # path('ezeneufotoindex/', views.ezeneufotoindex, name='ezeneufotoindex'),
    # path('ezebestfotoindex/', views.ezebestfotoindex, name='ezebestfotoindex'),
    # path('ezeneugenindex/', views.ezeneugenindex, name='ezeneugenindex'),
    # path('ezebestgenindex/', views.ezebestgenindex, name='ezebestgenindex'),
    ##NO NEED for this i hope will be after if b==b
    path('bestfoto/number/<int:pk>', views.BestFotovoltaicDetailView.as_view(), name = 'ezebestfotodetail'),
    path('bestgen/number/<int:pk>', views.BestGeneratorDetailView.as_view(), name = 'ezebestgendetail'),
    path('ezeneuwind/', views.NeuWindkraftIndexView.as_view(), name='ezeneuwindindex'),
    path('neuwind/number/<int:pk>', views.NeuWindkraftDetailView.as_view(), name = 'ezeneuwinddetail'),
    path('bestwind/number/<int:pk>', views.BestWindkraftDetailView.as_view(), name = 'ezebestwinddetail'),
    path('neufoto/number/<int:pk>', views.NeuFotovoltaicDetailView.as_view(), name = 'ezeneufotodetail'),
    

]

datebank/datebank/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView # new for login and logout
# from django.urls import path 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('accounts/', include('accounts.urls')), #for registration for new app	accounts
    path('cert82', include('certification82.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('login', TemplateView.as_view(template_name='login.html'), name='login'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datebank/certification82/templates/certification82/detailed_views/betreiber_detail.html
{% extends "base.html" %}
<!-- # detail which depends to the project id -->

{% block title %}
	Details index
{% endblock %}
{% block content %}

	<div class="jumbotron text-center">
		<h2>Object "{{object.name}}" details: {{ object.project_name }}</h2> 	
		<br>
	</div>
		<span class='col-md-6 ezeneu_left '>
		<table border=0 class="table table-hover table">
			
			<tr class= "thead-light">
				<th >Info Betreiber:</th> <th>{{ object.Zert_Firm }}</th><th>OK</th>
				{% if user.admin == True %}
				<th>Textmarke</th></tr>
				{% endif %}
			<tr ><th >Ansprechpartner:</th> <td><b>{{ object.name }}</b></td>
			{% if object.nameOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}
			{{ object.nameOK }}</td>
			{% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_AnspreTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>EZA-Betreiber:</th> <td> {{ object.EZA_Betreiber_Anspre }}</td>

				{% if object.EZA_Betreiber_AnspreOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}{{ object.EZA_Betreiber_AnspreOK }}</td>
				 {% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_AnspreTextmarke }}</td>
			{% endif %}</tr>
				</tr>
			<tr><th>Str, HausNr.:</th> <td> {{ object.EZA_Betreiber_StrNr }}</td>
			{% if object.EZA_Betreiber_StrNrOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}
			{{ object.EZA_Betreiber_StrNrOK}}</td>
			{% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_StrNrTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>PLZ, Ort:</th> <td> {{ object.EZA_Betreiber_PlzOrt }}</td>

			{% if object.EZA_Betreiber_PlzOrtOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}
			{{ object.EZA_Betreiber_PlzOrtOK }}</td>
			{% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_PlzOrtTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>Telefon:</th> <td> {{ object.EZA_Betreiber_Tel }}</td>

			{% if object.EZA_Betreiber_TelOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}
			{{ object.EZA_Betreiber_TelOK }}</td>
			{% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_TelTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>E-Mail:</th> <td> {{ object.EZA_Betreiber_Mail }}</td>
			{% if object.EZA_Betreiber_MailOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}
			{{ object.EZA_Betreiber_MailOK }}</td>
			{% if user.admin == True %}
			<td>{{ object.EZA_Betreiber_MailTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>Anlagenzertifikat Nummer:</th> <td> {{ object.Anlagenzert_Nr }}</td>
			{% if object.Anlagenzert_NrOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}{{ object.Anlagenzert_NrOK }}</td>
				 {% if user.admin == True %}
			<td>{{ object.Anlagenzert_NrTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>Projektnummer:</th> <td> {{ object.Projekt_Nr }}</td>
			{% if object.Projekt_NrOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}{{ object.Projekt_NrOK }}</td>
				 {% if user.admin == True %}
			<td>{{ object.Projekt_NrTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><th>Projekttittel:</th> <td> {{ object.Projekttitel }}</td>
			{% if object.ProjekttitelOK == True %}
				 <td class="bg-success">
				 {% else %}
				 <td class="bg-danger">
				 {% endif %}{{ object.ProjekttitelOK }}</td>
				 {% if user.admin == True %}
			<td>{{ object.ProjekttitelTextmarke }}</td>
			{% endif %}
		</tr>
			<tr><td><!-- <a href="{% url 'certification82:betreiberdetailview' object.id %}">View</a> -->	<a href="{% url 'certification82:betreiber_update' object.id %}">Aktualisieren</a>	 </td>
				<td><a href="{% url 'certification82:betreiber_delete' object.id %}">Löschen</a>
			</td></tr>
			<tr><th></th></tr>
			
		</table>
		<br>
		<!-- <table border=2 class="table-hover">
		
			{3% for proj in project %}
				{3% if proj.project_Nr == object.project_Nr %}
					<tr id="ezename"><th >{3{object.name}} BELONGS TO</th> <td><b>NEXT PROJECTS:</b></td></tr>
					<tr><th>NAME:</th> <td> {3{ proj.project_name }}</td></tr>
					<tr><td><a href="{3% url 'certification82:project_show' proj.id %}">Edit</a>	<a href="">Edit</a>
				{3% endif %}

			{3%endfor%}
			
		</table> -->
		
		</span>
	<br>

		
	<br>	
</div>

{% endblock %}

datebank/certification82/templates/certification82/detailed_views/project_detail.html
{% extends "base.html" %}
<!-- # detail which depends to the project id -->
{% block title %}
	Details index
{% endblock %}

{% block content %}
	
	<div class="card"> <div class="card-body">
		<p>Allgemeine Information zum Projekt: "{{ object.project_name }}"</p>
		<table border=0 class="table table-hover">
		<h1>
			<tr><th>{{ object.Projekt_NrTexmarke }}:</th> <td> {{ object.project_number }}</td></tr>
			<tr><th>{{ object.ProjekttitelTexmarke }}:</th> <td> {{ object.project_name }}</td></tr>
		</table>


		{% if user.admin == True %}
			<table border=0 class=" table table-hover">
				<tr>
					<th>Textmarke</th><th>Information</th><th>Daten</th>
				</tr>

				<tr><td>{{ object.Projekt_DateTexmarke }}:</td><td>Projekt Deadline Datum</td> <td> {{ object.project_deadline_date }}</td></tr>
				<tr><td>{{ object.betreiberTextmarke }}:</td> <td>EZA-Betreiber</td><td><a href="{% url 'certification82:betreiberdetailview' object.betreiber.id %}" > {{ object.betreiber }}</a></td></tr>
				<tr><td>{{ object.Zert_PartTextmarke }}:</td><td>Firma (Zertifikatsinhaber)</td> <td> <a href="{% url 'certification82:zertifikatsinhaberdetailview' object.zertifikatsinhaber.id %}" >{{ object.zertifikatsinhaber }}</td></tr></a>
				
				<tr><td>{{ object.netzbetreiberTextmarke }}:</td><td>Netzbetreiber</td> <td><a href="{% url 'certification82:netzbetreiberdetailview' object.netzbetreiber.id %}" > {{ object.netzbetreiber }}</a></td></tr>
				

			</table>
				<button type="button" class="btn btn"><a href="{% url 'certification82:project_update' object.id %}"><d class='text-dark'>Aktualisieren<d/></a></button>
 				<button type="button" class="btn btn-danger"><a href="{% url 'certification82:project_delete' object.id %}"><d class='text-light'>Löschen<d/></a></button>
	  			</d></a></button></d></a></button></d></a></button></div>

					

			{% endif %}
		
		<span class='col-md-6 ezeneu_left '>
			
		<table border=0 class="table-hover">
		
		{% for betr in betreiber %}
			<tr id="ezename"><th >Info Betreiber:</th> <td><b>{{ betr.Zert_Firm }}</b></td><td>OK</td></tr>
			<tr id="ezename"><th >{{betr.EZA_Betreiber_NameTextmarke}}:</th> <td><b>{{ betr.name }}</b></td>
			<td>{{ betr.nameOK }}</td></tr></tr>
			<tr><th>{{ betr.EZA_Betreiber_AnspreTextmarke }}:</th> <td> {{ betr.EZA_Betreiber_Anspre }}</td><td>{{ betr.EZA_Betreiber_AnspreOK }}</td></tr></tr>
			<tr><th>{{ betr.EZA_Betreiber_StrNrTextmarke }}:</th> <td> {{ betr.EZA_Betreiber_StrNr }}</td><td>{{ betr.EZA_Betreiber_StrNrOK}}</td></tr>
			<tr><th>{{ betr.EZA_Betreiber_PlzOrtTextmarke }}:</th> <td> {{ betr.EZA_Betreiber_PlzOrt }}</td><td>{{ betr.EZA_Betreiber_PlzOrtOK }}</td></tr></tr>
			<tr><th>{{ betr.EZA_Betreiber_TelTextmarke }}:</th> <td> {{ betr.EZA_Betreiber_Tel }}</td><td>{{ betr.EZA_Betreiber_TelOK }}</td></tr></tr>
			<tr><th>{{ betr.EZA_Betreiber_MailTextmarke }}:</th> <td> {{ betr.EZA_Betreiber_Mail }}</td><td>{{ betr.EZA_Betreiber_MailOK }}</td></tr></tr>
			<tr><th>{{ betr.Anlagenzert_NrTextmarke }}:</th> <td> {{ betr.Anlagenzert_Nr }}</td>
			<td>{{ betr.Anlagenzert_NrOK }}</td></tr></tr>
			<tr><th>{{ betr.Projekt_NrTextmarke }}:</th> <td> {{ betr.Projekt_Nr }}</td>
			<td>{{ betr.Projekt_NrOK }}</td></tr></tr>
			<tr><th>{{ betr.ProjekttitelTextmarke }}:</th> <td> {{ betr.Projekttitel }}</td>
			<td>{{ betr.ProjekttitelOK }}</td></tr></tr>
			{% if user.admin == True %}
			<tr><td><a href="{% url 'certification82:betreiberdetailview' betr.id %}">View</a>	<a href="">Edit</a>	<a href="">Delete</a></td></tr>
			<tr><th></th></tr>
			{% endif %}
		{%endfor%}
			<br><tr><td><a href="{% url 'certification82:new_betreiber' %}">Neu Betreiber</a></td></tr>
			
		{% for eze in zertifikatsinhaber %}

			<tr id="ezename"><th >Info Zertifikatsinhaber:</th> <td><b>{{ eze.Zert_Firm }}</b></td><td>OK</td></tr>
			<tr id="ezename"><th >{{ eze.EZA_BezeichnungTextmarke }}:</th> <td>{{ eze.EZA_Bezeichnung }}<td>{{ eze.EZA_BezeichnungOK }}</td></tr>
			</td></tr>
			<tr><th>{{ eze.Zert_PartTextmarke }}:</th> <td> {{ eze.Zert_Part }}</td>
			<td>{{ eze.Zert_PartOK }}</td></tr>
			<tr><th>{{ eze.Zert_FirmTextmarke }}:</th> <td> {{ eze.Zert_Firm }}</td>
			<td>{{ eze.Zert_FirmOK }}</td></tr>
			<tr><th>{{ eze.Zert_NrTextmarke }}:</th> <td> {{ eze.Zert_Nr }}</td>
			<td>{{ eze.Zert_NrOK }}</td></tr>
			<tr><th>{{ eze.Zert_PLZTextmarke }}:</th> <td> {{ eze.Zert_PLZ }}</td>
			<td>{{ eze.Zert_PLZOK }}</td></tr>
			<tr><th>{{ eze.Zert_TelTextmarke }}:</th> <td> {{ eze.Zert_Tel }}</td>
			<td>{{ eze.Zert_TelOK }}</td></tr></tr>
			<tr><th>{{ eze.Zert_FaxTextmarke }}:</th> <td> {{ eze.Zert_Fax }}</td>
			<td>{{ eze.Zert_FaxOK }}</td></tr>
			<tr><th>{{ eze.Zert_MailTextmarke }}:</th> <td> {{ eze.Zert_Mail }}</td>
			<td>{{ eze.Zert_MailOK }}</td></tr>
			
			<tr><th>{{ eze.Projekt_NrTextmarke }}:</th> <td> {{ eze.Projekt_Nr }}</td>
			<td>{{ eze.Projekt_NrOK }}</td></tr>
			<tr><td><a href="{% url 'certification82:eze_neu_show' eze.id %}">View</a>	<a href="">Edit</a>	<a href="">Delete</a></td></tr>
			<tr><th></th></tr>
		{%endfor%}
			
			<br><tr><td><a href="{% url 'certification82:new_zert' %}">Neu Zertifikatsinhaber</a></td></tr>
			
		{% for eze in netzbetreiber %}
			<tr id="ezename"><th >Info Netzbetreiber:</th> <td><b>{{ eze.NB_Name }}</b></td><td>OK</td></tr>
		
			<tr id="ezename"><th >{{ eze.NB_AnsprechTextmarke }}:</th> <td>{{ eze.NB_Ansprech }}
			<td>{{ eze.NB_AnsprechOK }}</td></tr>
			</td></tr>
			<tr><th>{{ eze.NB_NameTextmarke }}:</th> <td> {{ eze.NB_Name }}</td>
			<td>{{ eze.NB_NameOK }}</td></tr>
			<tr><th>{{ eze.NB_StrTextmarke }}:</th> <td> {{ eze.NB_Str }}</td>
			<td>{{ eze.NB_StrOK }}</td></tr>
			<tr><th>{{ eze.NB_PLZTextmarke }}:</th> <td> {{ eze.NB_PLZ }}</td>
			<td>{{ eze.NB_PLZOK }}</td></tr>
			<tr><th>{{ eze.NB_TelTextmarke }}:</th> <td> {{ eze.NB_Tel }}</td>
			<td>{{ eze.NB_TelOK }}</td></tr>
			<tr><th>{{ eze.NB_FaxTextmarke }}:</th> <td> {{ eze.NB_Fax }}</td>
			<td>{{ eze.NB_FaxOK }}</td></tr></tr>
			<tr><th>{{ eze.NB_MailTextmarke }}:</th> <td> {{ eze.NB_Mail }}</td>
			<td>{{ eze.NB_MailOK }}</td></tr>
			
			<tr><th>{{ eze.Registriernummer_NBTextmarke }}:</th> <td> {{ eze.Registriernummer_NB }}</td><td>{{ eze.Registriernummer_NBOK }}</td></tr>
			
			<tr><th>{{ eze.Projekt_NrTextmarke }}:</th> <td> {{ eze.Projekt_Nr }}</td>
			<td>{{ eze.Projekt_NrOK }}</td></tr>
			<tr><td><a href="{% url 'certification82:eze_neu_show' eze.id %}">View</a>	<a href="">Edit</a>	<a href="">Delete</a></td></tr>
			<tr><th></th></tr>
		


			<tr><th></th></tr>
		{%endfor%}
			<br><tr><td><a href="{% url 'certification82:new_netzbetreiber' %}">Neu Netzbetreiber</a></td></tr>
			{% if user.admin == True %}
				<p>You are authenticated as {{ user }} - ADMINISTRATOR.</p>
					{% for u in ProjectUser.objects.all %}
						USER: {{u}}
					{%endfor%}
			<tr><td></td></tr>
			{%endif%}
		</table><br>
		<a class="alert btn-success btn text-light" href="{% url 'certification82:new_projekt' %}">Neu Projekt</a>
	</div></div>
		</span>

{% endblock %}